import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "./components/LenisSmoothScroll";
import { InterestContextProvider } from "./context/InterestContextProvider";
import { WindowContextProvider } from "./context/WindowSizeContextProvider";
import StyledComponentsRegistry from "./components/styledCompRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apple Jane De Guzman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <LenisSmoothScroll> */}
        <WindowContextProvider>
          <InterestContextProvider>
            <StyledComponentsRegistry>
              {children}
            </StyledComponentsRegistry>
          </InterestContextProvider>
        </WindowContextProvider>
        {/* </LenisSmoothScroll> */}
      </body>
    </html>
  );
}
